[config]
schemaVersion = "0.0.1"


[package]
namespace = "zannc"
name = "KeepsakeExtender"
versionNumber = "1.0.0"
description = "Allows for the keepsake rack to hold more than 33 Keepsakes, important for creating new gods/keepsakes"
websiteUrl = "https://github.com/excellent-ae/zannc-KeepsakeExtender"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.67"
SGG_Modding-ModUtil = "4.0.1"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", "tools" ]
